version: "3"
services:
  gateway:
    image: jonasal/nginx-certbot:latest
    ports:
      - "80:80"
      - "443:443"
    environment:
      - CERTBOT_EMAIL
    volumes:
      - $MARS_DATA_DIR:/usr/share/nginx/html:ro
      - ./system/nginx.conf:/etc/nginx/user_conf.d/default.conf:ro
  server:
    image: mars_tile_server
    build: 
      context: .
      dockerfile: tools/tile-server/Dockerfile
    command: >
      gunicorn mars_tile_server:app
        --bind 0.0.0.0:8000
        --workers 8
        --worker-class uvicorn.workers.UvicornWorker
    environment:
      - FOOTPRINTS_DATABASE
      - MOSAIC_CONCURRENCY 
    expose:
      - 8000
    volumes:
      - $MARS_DATA_DIR:/mars-data
  database:
    image: postgis/postgis:13-3.1
    ports:
      - "54321:5432"
    environment:
      - POSTGRES_DB=aeolis_dorsa
      - POSTGRES_PASSWORD
    volumes:
      - db_cluster:/var/lib/postgresql/data
  frontend:
    image: ghcr.io/davenquinn/mars-lab-frontend:main
  db_backup:
    image: ghcr.io/uw-macrostrat/pg-backup-service:latest
    environment:
      - DB_NAME=footprints
      - DB_BACKUP_PREFIX=mars_lab
      - PGHOST=database
      - PGPASSWORD=$POSTGRES_PASSWORD
      - S3_ENDPOINT
      - SCHEDULE=@weekly
      - DB_BACKUP_MAX_N=5
      - S3_ACCESS_KEY
      - S3_SECRET_KEY
      - S3_BACKUP_BUCKET=macrostrat-db-backups
volumes:
  db_cluster: