version: "3"
services:
  gateway:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - $MARS_DATA_DIR:/usr/share/nginx/html:ro
      - ./system/nginx.conf:/etc/nginx/conf.d/default.conf:ro
  server:
    build: tools/tile-server
    command: uvicorn --host 0.0.0.0 --port 8000 --root-path /tiles mars_tile_server:app
    expose:
      - 8000
    volumes:
      - $MARS_DATA_DIR:/mars-data:ro
  database:
    image: postgis/postgis:13-3.1
    ports:
      - "54321:5432"
    environment:
      - POSTGRES_DB=aeolis_dorsa
      - POSTGRES_PASSWORD
    volumes:
      - db_cluster:/var/lib/postgresql/data
volumes:
  db_cluster: