version: "3"
services:
  gateway:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - $MARS_DATA_DIR:/usr/share/nginx/html:ro
  database:
    image: postgis/postgis:13-3.1
    ports:
      - "54321:5432"
    environment:
      - POSTGRES_DB=aeolis_dorsa
      - POSTGRES_PASSWORD
    volumes:
      - db_cluster:/var/lib/postgresql/data
volumes:
  db_cluster: