# https://code.visualstudio.com/docs/containers/debug-common
version: '3'
services:
  tile_server:
    command: >
      python
        -m debugpy --listen 0.0.0.0:5678
        -m uvicorn
          --host 0.0.0.0
          --port 8000
          --reload
          mars_tiler:app
    volumes:
      - ./tools/tile-server:/tools/tile-server
    expose:
      - 8000
    ports:
      - 5678:5678
